# Generated by Django 2.2.2 on 2019-06-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='consulta_realizada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gerencial.Consulta'),
        ),
    ]
