# Generated by Django 2.2.2 on 2019-06-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0002_procedimiento_consulta_realizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Precio Base'),
        ),
    ]
