# Generated by Django 2.2.2 on 2019-06-19 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0003_consulta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotemedicamento',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='precio_producto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Precio unitario'),
        ),
    ]
