# Generated by Django 2.2.2 on 2019-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0005_pago_procedimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='fechaUltimaModificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
    ]
