# Generated by Django 2.2.2 on 2019-06-22 08:19

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0005_pago_procedimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccionCasa',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccionTrabajo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefonoCasa',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefonoTrabajo',
        ),
        migrations.AddField(
            model_name='lotemedicamento',
            name='fecha_entrada',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de entrada'),
        ),
        migrations.AddField(
            model_name='receta',
            name='nombreReceta',
            field=models.CharField(default='Receta', max_length=100, verbose_name='Nombre de la receta'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fechaCita',
            field=models.DateField(verbose_name='Fecha de Cita'),
        ),
        migrations.AlterField(
            model_name='lotemedicamento',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de entrada'),
        ),
        migrations.AlterField(
            model_name='lotemedicamento',
            name='fecha_vencimiento',
            field=models.DateField(verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
