# Generated by Django 2.2.2 on 2019-07-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0006_odontograma_fechaultimamodificacion'),
        ('gerencial', '0006_auto_20190622_0819'),
    ]

    operations = [
    ]
