# Generated by Django 2.2.2 on 2019-06-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencial', '0006_auto_20190622_0819'),
        ('gerencial', '0006_odontograma_fechaultimamodificacion'),
    ]

    operations = [
    ]
